### ISSUE TITLE
Tab Sizes in Nested Lists is Off

### ISSUE THREAD

**Issue by mleo2003** [radekkozak/discordian#12]
When making a nested list of things, with or without bullet points, I use tabs to indent nested elements. The first level of indented items move the cursor pretty far over, but the 2nd tab actually makes it move "backwards", and then keeps going. This only applies in Edit Mode, in Preview Mode, the different levels all work fine (with the lines connecting things as they should).

**Comment by radekkozak** [comment]
Hi, Radek here. Thanks for taking the time to report the issue. I think with a pretty good guess i know what might be the cause of the behaviour you're talking about. It's probably caused by a simple setting that enabled me to make the pretty task lists working in Editor Mode - now i see it may be the cause of issues in other lists. 

Just to be on the same page and to ensure i'm talking about sam issue here it would great help if you could provide screenshots of the issue (here and with other issue you reported) I'd be very much obliged 

And if it is what i suspect it is i might be able to provide easy fix for you even before it would make into next release of Discordian (coming up soon)

Thanks

**Comment by radekkozak** [comment]
Also please let me know - just in case - if you're using Obsidian's `Smart Intend Lists`. Thanks

**Comment by mleo2003** [comment]
Thanks for the fast reply. I do indeed have Smart indent lists on, but it also does it without it.

Also, your hunch about it being related to task lists (and bulleted lists in general) seems right, it doesn't do it for normal indentations, but does for bullet list indentations.

![Screenshot at 2021-01-09 12-25-34](https://user-images.githubusercontent.com/3462000/104108035-2d9fd480-5276-11eb-8e78-16e1bc8aae57.png)

The screenshot shows the difference between the two.

**Comment by radekkozak** [comment]
Thanks for the screen, as i suspected. I already pinned down the problem. Easy fix for right now is to remove lines 1564-1566 in Discordian.css in your vault. I'm talking this section below

https://github.com/radekkozak/discordian/blob/856bf057380285c1817e6d7040d64402d2c62967/obsidian.css#L1564

But i would need to rethink how i could still provide pretty task lists in Editor without this. 

I would be glad if you could tell me one thing: does the big indentation would really bother assuming that the indentations would work and not moving "backwards" ? Otherwise - because of the way Obsidian targets list the - only thing i can do right now is for lists to have original indentations in Editor (those look kinda ugly on tasks). I attach two screenshots how that looks after reverting changes to Obsidian lists defaults (on regular lists it's ok, not so much on tasks i think - but that's better than the bug you're reporting i think)

![Screen Shot 2021-01-09 at 21 47 23](https://user-images.githubusercontent.com/2744747/104108460-19cf8f00-52c5-11eb-9713-11cce4a6c622.png)

![Screen Shot 2021-01-09 at 21 47 01](https://user-images.githubusercontent.com/2744747/104108457-1805cb80-52c5-11eb-863d-5d6e8ee3826a.png)

**Comment by mleo2003** [comment]
Thanks for the temp fix, I'll play with that in a bit.

As for task lists, I haven't started using them myself, though now I believe I will. I'd be fine if it were just larger indents all across, so that things in edit mode still lined up, and I could tell about which level I was at (i.e. that I could see something indented 2 times was "within" the item that was 1, instead of looking like it was outside of it). If everything was the same, with larger tabs all across, that would be fine with me at least.

**Comment by radekkozak** [comment]
Cool, i think i can make it work. It would look sth like below - bigger indents but behaving correctly and coherently to the intended list level - already tried with Tab and Shift+Tab and it seems ok, but will test further

Anyway, thank you for your feedback, it's very helpful

![Screen Shot 2021-01-09 at 23 26 05](https://user-images.githubusercontent.com/2744747/104109840-23132880-52d2-11eb-8722-425ab9036b2d.png)
