### ISSUE TITLE
Horizontal scrolling not available for long tables inside Preview mode

### ISSUE THREAD

**Issue by Gadwood** [radekkozak/discordian#20]
![Capture d’écran, le 2021-01-25 à 19 37 21](https://user-images.githubusercontent.com/69422318/105783569-c015c880-5f44-11eb-956b-bc5470a76278.png)
![Capture d’écran, le 2021-01-25 à 19 40 37](https://user-images.githubusercontent.com/69422318/105783795-5944df00-5f45-11eb-8613-72404ef764ef.png)
[Corpus de connaissances en management de projet (PMBoK).md.zip](https://github.com/radekkozak/discordian/files/5870418/Corpus.de.connaissances.en.management.de.projet.PMBoK.md.zip)

**Comment by Gadwood** [comment]
Ho last update juste remove the bug! As a second issue is it normal that the "X" to close the setting page is offset of center?

**Comment by radekkozak** [comment]
Hi again Guillaume, no - the "X" should be all OK. From what i see you do not use Discordian's fonts (Catamaran) which as - from my description in the repo: 

**IMPORTANT**: For best experience possible, please download the fonts and install them in your system before using the theme. **Provided fonts closely resemble those in Discord app and are sort of required here**

[Download fonts](https://github.com/radekkozak/discordian/raw/master/media/fonts.zip) and all should be A-OK

**Comment by radekkozak** [comment]
As to Horizontal ScrollBar - do you still have the issue ? I designed the theme so there is no horizontal scrollbar because it is visually cluttering whole note but i can see i missed the tables so while checking your provided note in zip file i see the bar and can scroll. 

To be honest i would love to remove it in next release, because - same as with long codeblocks - you can easily scroll such parts with **Shift" button. I will have to think about it though

**Comment by Gadwood** [comment]
For the issue it’s gone. I did not knew we can side scroll with shift. Thank you

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Radek Kozak <notifications@github.com>
Envoyé : Wednesday, January 27, 2021 4:39:44 AM
À : radekkozak/discordian <discordian@noreply.github.com>
Cc : Gadwood <guillaume@gadbois.cc>; Author <author@noreply.github.com>
Objet : Re: [radekkozak/discordian] Horizontal scrolling bar (#20)


As to Horizontal ScrollBar - do you still have the issue ? I designed the theme so there is no horizontal scrollbar because it is visually cluttering whole note but i can see i missed the tables so while checking your provided note in zip file i see the bar and can scroll.

To be honest i would love to remove it in next release, because - same as with long codeblocks - you can easily scroll such parts with **Shift" button. I will have to think about it though

**Comment by derwish-pro** [comment]
Hello. I have the same bug. No horizontal bar on page with large table. Last theme and plugin.

**Comment by radekkozak** [comment]
Hi @derwish-pro , as i already explained answering @Gadwood - there is no horizontal bar in note "by design" because it only clutters the view but you **should easily scroll everything that requires horizontal scrollbar by scrolling with Shift** pressed. Have you tried that ?

Is the horizontal scrollbar necessary for you - i could provide a quick snippet fix for you in such case if you can't do with the solution above. 

Also it would be very helpful if you could attach the problematic note so i could debug the problem in depth. Thanks !

**Comment by derwish-pro** [comment]
It works with Shift only in the edit mode. In view mode it doesn`t.

**Comment by radekkozak** [comment]
Hi @derwish-pro , sorry for delay. Yes i was able to reproduce the problem - indeed you were right, something was off with Preview mode. I already have working solution - so thank you for spotting this. Will be out in next version with other fixes. 

Still i'm for no horizontal bars if there is Shift+scroll working - it looks so much better on overall UI. But i'm wondering what do you think - is the lack of visual h-scrollbar disturbing ? Or maybe i should just make it an option in the plugin for the user to decide - would that be ok ? Let me know

Thanks once again for reporting the issue, appreciated

**Comment by derwish-pro** [comment]
It would be great to have the option
